# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy
    - task update-version-file

dist: build

archives:
  - format_overrides:
      - goos: windows
        format: zip

builds:
  - main: './main.go'
    binary: 'project-indexer'
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.build={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    targets:
      - linux_amd64
      - darwin_arm64
      - darwin_amd64
      - windows_amd64

# brews:
    # - name: 'project-indexer'
    #   homepage: 'https://github.com/permafrost-dev/project-indexer'
    #   description: 'check if a project has any changed source files'
    #   license: "MIT"
    #     repository:
    #       owner: 'permafrost-dev'
    #       name: homebrew-project-indexer
    #       branch: main

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
